
import { Country, Recipe } from './types';

export const ALL_COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', region: 'Asia' },
  { name: 'Albania', code: 'AL', region: 'Europe' },
  { name: 'Algeria', code: 'DZ', region: 'Africa' },
  { name: 'Andorra', code: 'AD', region: 'Europe' },
  { name: 'Angola', code: 'AO', region: 'Africa' },
  { name: 'Antigua and Barbuda', code: 'AG', region: 'Americas' },
  { name: 'Argentina', code: 'AR', region: 'Americas' },
  { name: 'Armenia', code: 'AM', region: 'Asia' },
  { name: 'Australia', code: 'AU', region: 'Oceania' },
  { name: 'Austria', code: 'AT', region: 'Europe' },
  { name: 'Azerbaijan', code: 'AZ', region: 'Asia' },
  { name: 'Bahamas', code: 'BS', region: 'Americas' },
  { name: 'Bahrain', code: 'BH', region: 'Asia' },
  { name: 'Bangladesh', code: 'BD', region: 'Asia' },
  { name: 'Barbados', code: 'BB', region: 'Americas' },
  { name: 'Belarus', code: 'BY', region: 'Europe' },
  { name: 'Belgium', code: 'BE', region: 'Europe' },
  { name: 'Belize', code: 'BZ', region: 'Americas' },
  { name: 'Benin', code: 'BJ', region: 'Africa' },
  { name: 'Bhutan', code: 'BT', region: 'Asia' },
  { name: 'Bolivia', code: 'BO', region: 'Americas' },
  { name: 'Brazil', code: 'BR', region: 'Americas' },
  { name: 'Bulgaria', code: 'BG', region: 'Europe' },
  { name: 'Cambodia', code: 'KH', region: 'Asia' },
  { name: 'Canada', code: 'CA', region: 'Americas' },
  { name: 'Chile', code: 'CL', region: 'Americas' },
  { name: 'China', code: 'CN', region: 'Asia' },
  { name: 'Colombia', code: 'CO', region: 'Americas' },
  { name: 'Denmark', code: 'DK', region: 'Europe' },
  { name: 'Egypt', code: 'EG', region: 'Africa' },
  { name: 'Ethiopia', code: 'ET', region: 'Africa' },
  { name: 'France', code: 'FR', region: 'Europe' },
  { name: 'Germany', code: 'DE', region: 'Europe' },
  { name: 'Greece', code: 'GR', region: 'Europe' },
  { name: 'India', code: 'IN', region: 'Asia' },
  { name: 'Indonesia', code: 'ID', region: 'Asia' },
  { name: 'Italy', code: 'IT', region: 'Europe' },
  { name: 'Japan', code: 'JP', region: 'Asia' },
  { name: 'Kenya', code: 'KE', region: 'Africa' },
  { name: 'Mexico', code: 'MX', region: 'Americas' },
  { name: 'Nigeria', code: 'NG', region: 'Africa' },
  { name: 'Norway', code: 'NO', region: 'Europe' },
  { name: 'Peru', code: 'PE', region: 'Americas' },
  { name: 'Philippines', code: 'PH', region: 'Asia' },
  { name: 'Spain', code: 'ES', region: 'Europe' },
  { name: 'Thailand', code: 'TH', region: 'Asia' },
  { name: 'USA', code: 'US', region: 'Americas' },
  { name: 'Vietnam', code: 'VN', region: 'Asia' },
  // ... adding more programmatically or as needed in UI
].sort((a, b) => a.name.localeCompare(b.name));

export const FEATURED_RECIPES: Recipe[] = [
  {
    id: '1',
    name: 'Classic Margherita Pizza',
    country: 'Italy',
    image: 'https://picsum.photos/seed/pizza/800/600',
    description: 'The authentic taste of Naples with fresh basil, mozzarella, and tomato sauce.',
    ingredients: ['Pizza Dough', 'Tomato San Marzano', 'Mozzarella di Bufala', 'Fresh Basil', 'Extra Virgin Olive Oil'],
    instructions: ['Roll out dough', 'Apply tomato sauce', 'Add mozzarella', 'Bake at 500F', 'Add fresh basil'],
    prepTime: '20 mins',
    difficulty: 'Easy'
  },
  {
    id: '2',
    name: 'Sushi Moriawase',
    country: 'Japan',
    image: 'https://picsum.photos/seed/sushi/800/600',
    description: 'A delicate selection of premium raw fish over seasoned vinegared rice.',
    ingredients: ['Sushi Grade Tuna', 'Sushi Grade Salmon', 'Sushi Rice', 'Nori Sheets', 'Wasabi'],
    instructions: ['Cook sushi rice', 'Slice fish thinly', 'Form rice balls', 'Place fish on rice', 'Serve with soy sauce'],
    prepTime: '45 mins',
    difficulty: 'Hard'
  },
  {
    id: '3',
    name: 'Tacos al Pastor',
    country: 'Mexico',
    image: 'https://picsum.photos/seed/tacos/800/600',
    description: 'Thinly sliced marinated pork with pineapple, onions, and cilantro.',
    ingredients: ['Pork Shoulder', 'Achiote Paste', 'Pineapple', 'Corn Tortillas', 'Cilantro'],
    instructions: ['Marinate pork', 'Grill with pineapple', 'Slice thinly', 'Serve on tortillas', 'Top with garnish'],
    prepTime: '30 mins',
    difficulty: 'Medium'
  }
];
